(function () {
    'use strict';

    window.SimpAICanvasWorkbenchCanvasAgent = Object.assign({}, window.SimpAICanvasWorkbenchCanvasAgent || {}, {
        CANVAS_AGENT_PRESET_QUEUE_STORAGE_KEY: 'simpai.canvas.agentPresetQueues.v1',
        CANVAS_AGENT_DEFAULT_T2I_PRESET_QUEUE: ['Z-imageT'],
        CANVAS_AGENT_DEFAULT_EDIT_PRESET_QUEUE: ['Flux2-KleinEdit'],
        CANVAS_AGENT_DEFAULT_I2V_PRESET_QUEUE: ['Wan(I2V)', 'Dasiwa(I2V)'],
        CANVAS_AGENT_DEFAULT_T2V_PRESET_QUEUE: ['Wan(T2V)', 'Wan-TTP'],
        CANVAS_AGENT_DEFAULT_VIDEO_EDIT_PRESET_QUEUE: ['Bernini-VideoEdit', 'Wan-Extent', 'Dasiwa-Extent'],
        CANVAS_AGENT_DEFAULT_AUDIO_TO_VIDEO_PRESET_QUEUE: ['LTX2.3(TA2V)', 'LTX2.3(IA2V)'],
        CANVAS_AGENT_DEFAULT_AUDIO_IMAGE_TO_VIDEO_PRESET_QUEUE: ['LTX2.3(IA2V)', 'LTX2.3(TA2V)'],
        CANVAS_AGENT_DEFAULT_VIDEO_OUTPAINT_PRESET: 'LTX-Outpaint',
        CANVAS_AGENT_DEFAULT_VIDEO_ERASE_PRESET: 'Wan-Remover',
        CANVAS_AGENT_DEFAULT_VIDEO_REPLACE_PRESET: 'Bernini-VideoEdit',
        CANVAS_AGENT_DEFAULT_VIDEO_UPSCALE_PRESET: 'Nvidia-VSR',
        CANVAS_AGENT_DEFAULT_AUDIO_PRESET_QUEUE: [],
        CANVAS_AGENT_PRESET_STATUS_CACHE_TTL_MS: 5 * 60 * 1000,
        CANVAS_AGENT_PRESET_STATUS_SCAN_CONCURRENCY: 4,
        CANVAS_AGENT_MAX_IMAGE_REFERENCES: 3,
        CANVAS_AGENT_MAX_EXTRA_IMAGE_REFERENCES: 2,
        CANVAS_AGENT_MAX_VIDEO_REFERENCES: 1,
        CANVAS_AGENT_MAX_AUDIO_REFERENCES: 1,
        CANVAS_AGENT_MAX_TEXT_REFERENCES: 4,
        CANVAS_AGENT_ASPECT_OPTIONS: [
            { key: 'auto', label: 'Auto', icon: 'fa-image', value: '' },
            { key: '1:1', label: '1:1', value: '1024*1024' },
            { key: '16:9', label: '16:9', value: '1344*768' },
            { key: '9:16', label: '9:16', value: '768*1344' },
            { key: '4:3', label: '4:3', value: '1152*864' },
            { key: '3:4', label: '3:4', value: '864*1152' },
            { key: '2:3', label: '2:3', value: '832*1216' },
            { key: '3:2', label: '3:2', value: '1216*832' },
            { key: '7:4', label: '7:4', value: '1344*768' },
            { key: '4:7', label: '4:7', value: '768*1344' }
        ],
        createDefaultSettings(versionChoices) {
            const versions = Array.isArray(versionChoices) ? versionChoices : [];
            return {
                enabled: true,
                executionRoute: 'programmatic',
                promptStrategy: 'ask',
                rewriteModel: versions[0] || 'Qwen3.5-9B-abliterated-Q4_K_M',
                videoFrames: 25,
                t2iPresetMode: 'auto',
                t2iPreset: '',
                editPresetMode: 'auto',
                editPreset: '',
                i2vPresetMode: 'auto',
                i2vPreset: '',
                t2vPresetMode: 'auto',
                t2vPreset: '',
                videoEditPresetMode: 'auto',
                videoEditPreset: '',
                audioPresetMode: 'auto',
                audioPreset: '',
                outpaintPreset: 'OneKey-Outpaint',
                erasePreset: 'Eraser',
                replacePreset: 'Swap+',
                upscalePresetMode: 'uov_auto',
                upscalePreset: '',
                videoOutpaintPreset: 'LTX-Outpaint',
                videoErasePreset: 'Wan-Remover',
                videoReplacePreset: 'Bernini-VideoEdit',
                videoEditQuickToolDefaultMigrated: false,
                videoUpscalePreset: 'Nvidia-VSR',
                outpaintUpPercent: 15,
                outpaintDownPercent: 15,
                outpaintLeftPercent: 15,
                outpaintRightPercent: 15,
                customApiCollapsed: true,
                customProvider: 'openai',
                customApiName: 'OpenAI',
                customApiFormat: 'openai_compatible',
                customBaseUrl: 'https://api.openai.com/v1',
                customModel: '',
                customSupportsImages: true,
                attachPaused: true,
                minimized: false,
                panelPosition: null,
                bubblePosition: null,
                allowPresetInstructionOverride: true
            };
        }
    });
})();
